<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\TransportationSystem.Application\\TransportationSystem.Application.csproj" />
    <ProjectReference Include="..\\TransportationSystem.Infrastructure\\TransportationSystem.Infrastructure.csproj" />
  </ItemGroup>
</Project>
